### PR TITLE
Fix build with Node v12

### PR DESCRIPTION
**Pull request by orgads**
Fixes: #14

### CODE REVIEW

**Comment by bretcope** [comment]
Thanks @orgads. I don't really do anything with node.js anymore. Would you be interested in maintaining this package?

**Comment by orgads** [comment]
Ok

**Comment by bretcope** [comment]
@orgads I've added you as a collaborator on GitHub. Do you have an npm user?

**Comment by orgads** [comment]
Thanks. Yes, orgads@gmail.com.

**Comment by orgads** [comment]
Sorry, the npm username is orgads.

**Pull request merged**
